### ISSUE TITLE
Answers to following question?

### ISSUE THREAD

**Issue by coodoo** [jorendorff/talks#2]
```
But did you think about how we detect that we've got a conflict to begin with?
Did you consider that we can also get a similar pair of events in a single editor, with no conflicts?
```

Just wondering what's the answers to above questions? :)

**Comment by jorendorff** [comment]
Good questions.

> But did you think about how we detect that we've got a conflict to begin with?

CRDTs dodge this issue. With CRDTs, the whole system is designed so that **there's no such thing as a conflict.** Edits can happen in any order, with the same result.

(However, conflicts are not impossible to detect, in systems where they can occur. You can just look at two edits and ask: *Does it matter which of these happened first?* And: *Is it possible other peers disagree with me about which one happened first?* If so, there may be a conflict.)

> Did you consider that we can also get a similar pair of events in a single editor, with no conflicts?

Well, the talk is about how to cope when events happen in a different order in different places. With a single editor, that's not an issue.
